nodes = {
  "master" => {"memory" => "1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip" => "100"}, 
  "node1" => {"memory" => "1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip" => "101"}, 
  "node2" => {"memory" => "1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip" => "102"},
  "node3" => {"memory" => "1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip" => "103"}
}


Vagrant.configure("2") do |configuration|
  
  nodes.each do |name,config|
    configuration.vm.define "#{name}" do |machine|
      machine.vm.box = "#{config["image"]}"
      machine.vm.hostname = "#{name}"
      #machine.vm.network "public_network", bridge: "eno2"
      machine.vm.network "private_network", ip: "192.168.56.#{config["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = config["memory"]
        vb.cpus = config["cpu"]
      end 
      machine.vm.provision "shell", path: "install-docker.sh"
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "node.sh"
      end
    end 
  end
end